### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by pjlasl** [pillopk/tablefactory#3]
How can I use the angular filters when loading the table?

For example:

I am currently loading a standard html table using {{ dollarvalue | currency }}

How can I do this using your table?

I tried to use the formatter but it doesn't work...

```
function currencyFormatter(value, record) {
    return '{{' + value + ' | currency }}';                       
}
```

It outpus as {{2516.43 | currency }}

Any help would be greatly appreciated

**Comment by abelrgr** [comment]
@pjlasl You could use the currency $filter from Angular

``` javascript
function currencyFormatter(value, record) {
      return $filter('currency')(value, 'USD$');
}
```

https://docs.angularjs.org/api/ng/filter/currency

**Comment by pjlasl** [comment]
thanks
