### ISSUE TITLE
Jquery is always required?

### ISSUE THREAD

**Issue by abelrgr** [pillopk/tablefactory#4]
I just saw the getting started but it say:

`TableFactory is an angular module to create tables, to add to your project simply add 'ngTableFactory' to angular dependancies. Require 'angular-sanitize.js'.`

``` javascript
var app = angular.module("testApp", ["ngSanitize", "ngTableFactory"]);
```

But when it's not added Jquery the code throws an error:

``` javascript
var element = angular.element(document).find("#test");
var options = {
        columns: [{
            field: "FirstName",
            caption: "Name",
            sortable: true
        }],
        selection: {
            canSelect: true
        },
        data: [{
            FirstName: 'Test',
        }]
    };
    var factory = TableFactory.create(element, options);
```

`console: ReferenceError: $ is not define`

Maybe can be used angular.element(document).find(...) using Jqlite instead of Jquery

**Comment by pillopk** [comment]
The factory is based on Bootstrap features which requires Jquery.
Dependency cannot be removed...
